<section class="row">
    <div class="col-md-4 offset-md-8">
        <?php
        $error = $_SESSION['error'] ?? [];
        $success = $_SESSION['success'] ?? [];

        unset($_SESSION['error']);
        unset($_SESSION['success']);

        foreach ($error as $eachError) {
            echo "
                <div class='alert alert-danger'>
                    <strong>Erro! </strong>
                    {$eachError}.
                </div>
            ";
        }

        foreach ($success as $eachSuccess) {
            echo "
                <div class='alert alert-success'>
                    <strong>Pronto! </strong>
                    {$eachSuccess}.
                </div>
            ";
        }

        ?>
    </div>
</section>