<section class="row mt-5">

    <div class="col-md-6 card card-body">
        <form action="" method="post">
            <label for=name>Nome:</label>
            <input type="text" class="form-control" name="name" id="name"><br>

            <label for=descricao>Descrição:</label>
            <textarea class=" form-control" name="description" id="description>"> </textarea>
            <br>

            <button class="btn btn-primary btn-block" name="button"> Enviar </button>
    </div>

</section>