<section class="row mt-5">
  <div class="col-md-6">
    <div class="card card-body">
      <h2>Nova Categoria</h2>

      <form action="" method="post">
        <label for="name">Nome: </label>
        <input type="text" class="form-control" name="name" id="name">
        <br>

        <label for="description">Descrição: </label>
        <textarea class="form-control" name="description" id="description"></textarea>
        <br>

        <button class="btn btn-primary btn-block" name="button">
          Enviar
        </button>
        <a href="/categorias" class="btn btn-light btn-block btn-sm">Voltar</a>
      </form>
    </div>
  </div>
</section>
