<section>
    <div class="col-md-12">
        <div class="card card-body">
            <h2>Categorias</h2>
            <div class="text-right">
                <a href="/nova-categoria" class="btn btn-outline-primary">Nova Categoria</a>
            </div>

            <table class="table table-hover table-striped mt-4">
                <thead class="thead-dark text-center">
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Ações</th>
                </thead>
                <tbody class="text-center">
                <?php
                    foreach ($data['categories'] as $category) {
                        echo "
                        <tr>
                            <td>{$category->getId()}</td>
                            <td>{$category->getName()}</td>
                            <td>{$category->getDescription()}</td>
                            <td>
                                <a href='/excluir-categoria' class='btn btn-danger'>Excluir</a>
                                <a href='/editar-categoria' class='btn btn-warning'>Editar</a>
                            </td>
                        </tr>
                        ";
                    }
                ?>
                </tbody>

            </table>


        </div>
    </div>
</section>