<section class="row mt-5">
  <div class="col-md-12">
    <div class="card card-body">
      <h2>Categorias</h2>

      <div class="text-right">
        <a href="/nova-categoria" class="btn btn-outline-primary">Nova Categoria</a>
      </div>

      <table class="table table-hover table-striped mt-4">
        <thead class="thead-dark">
          <th>Nome</th>
          <th>Descrição</th>
          <th>Ações</th>
        </thead>
        <tbody>
          <tr>
            <td>Informática</td>
            <td>Produtos de Tecnologia</td>
            <td>
              <a href="/excluir-categoria" class="btn btn-danger">Excluir</a>
              <a href="/editar-categoria" class="btn btn-warning">Editar</a>
            </td>
          </tr>
          
          <tr>
            <td>Informática</td>
            <td>Produtos de Tecnologia</td>
            <td>
              <a href="/excluir-categoria" class="btn btn-danger">Excluir</a>
              <a href="/editar-categoria" class="btn btn-warning">Editar</a>
            </td>
          </tr>
          <tr>
            <td>Informática</td>
            <td>Produtos de Tecnologia</td>
            <td>
              <a href="/excluir-categoria" class="btn btn-danger">Excluir</a>
              <a href="/editar-categoria" class="btn btn-warning">Editar</a>
            </td>
          </tr>
          <tr>
            <td>Informática</td>
            <td>Produtos de Tecnologia</td>
            <td>
              <a href="/excluir-categoria" class="btn btn-danger">Excluir</a>
              <a href="/editar-categoria" class="btn btn-warning">Editar</a>
            </td>
          </tr>

        </tbody>
      </table>
    </div>
  </div>
</section>
