<section class="row mt-5">

    <div class="col-md-6 card card-body">
        <form action="" method="post">
            <label for=name>Nome</label>
            <input type="text" class="form-control" name="name" id="name"><br>

            <label for="categoria">Categoria</label>
            <select class="form-control"   >
                <option> -- Selecione -- </option>
                <option>Informatica</option>
            </select><br>
            <div class="row">
                <div class="col-md-4"   >
                    <label for=quantidade>Quantidade</label>
                    <input type="text" class="form-control" name="quantidade" id="quantidade"><br>
                </div>
            </div>  
            <label for="descricao">Descrição</label>    
            <textarea class=" form-control" name="descricao" id="descricao"> </textarea>
            <br>

            <button class="btn btn-primary btn-block" name="button"> Enviar </button>
    </div>

</section>