<section>
    <div class="col-md-12">
        <div class="card card-body">
            <h2>Produtos</h2>
            <div class="text-right">
                <a href="/novo-produto" class="btn btn-outline-primary">Novo Produto</a>
            </div>

            <table class="table table-hover table-striped mt-4">
                <thead class="thead-dark text-center">
                    <th>Nome</th>
                    <th>Categoria</th>
                    <th>Quantidade</th>
                    <th>Descrição</th>
                    <th>Ações</th>
                </thead>
                <tbody class="text-center">
                <?php
                foreach ($data['products'] as $product) {
                    echo "<tr>
                        <td>{$product->getName()}</td>
                        <td title='{$product->getCategory()->getDescription()}'>{$product->getCategory()->getName()}</td>
                        <td>{$product->getQuantity()}</td>
                        <td>{$product->getDescription()}</td>
                        <td></td>
                    </tr>";
                }
                ?>
                </tbody>

            </table>


        </div>
    </div>
</section>