<section>
    <div class="">
        <div class="col-md-6 card card-body">
            <form method="post">
                <label for="nome">Nome:</label>
                <input type="text" name="name" id="nome" class="form-control">
                <label for="email">Email:</label>
                <input type="mail" name="email" id="email" class="form-control">
                <label for="password">Senha:</label>
                <input type="password" name="password" id="password" class="form-control">
                <div class="form-check mt-3">
                    <input type="checkbox" class="form-check-input">
                    <label class="form-check-label">Status</label>
                </div>
                
                <button class="btn btn-primary btn-block mt-3">Cadastrar</button>
            </form>

        </div>

    </div>

</section>