<section>
    <div class="col-md-12">
        <div class="card card-body">
            <h2>Usuários</h2>
            <div class="text-right">
                <a href="/novo-usuario" class="btn btn-outline-primary">Nova Usuário</a>
            </div>

            <table class="table table-hover table-striped mt-4">
                <thead class="thead-dark text-center">
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Status</th>
                    <th>Ações</th>
                </thead>
                <tbody class="text-center">
                    <tr>
                        <td>Cliff Baptista</td>
                        <td>cliffmorais@gmail.com</td>
                        <td>Ativo</td>
                        <td>
                            <a href="/excluir-categoria" class="btn btn-danger">Excluir</a>
                            <a href="/editar-categoria" class="btn btn-warning">Editar</a>
                        </td>
                    </tr>
                    <tr>
                        <td>Cliff Baptista</td>
                        <td>cliffmorais@gmail.com</td>
                        <td>Ativo</td>
                        <td>
                            <a href="/excluir-categoria" class="btn btn-danger">Excluir</a>
                            <a href="/editar-categoria" class="btn btn-warning">Editar</a>
                        </td>
                    </tr>
                    <tr>
                        <td>Cliff Baptista</td>
                        <td>cliffmorais@gmail.com</td>
                        <td>Ativo</td>
                        <td>
                            <a href="/excluir-categoria" class="btn btn-danger">Excluir</a>
                            <a href="/editar-categoria" class="btn btn-warning">Editar</a>
                        </td>
                    </tr>
                    <tr>
                        <td>Cliff Baptista</td>
                        <td>cliffmorais@gmail.com</td>
                        <td>Ativo</td>
                        <td>
                            <a href="/excluir-categoria" class="btn btn-danger">Excluir</a>
                            <a href="/editar-categoria" class="btn btn-warning">Editar</a>
                        </td>
                    </tr>
                </tbody>

            </table>


        </div>
    </div>
</section>