

<section class="row mt-5 text-white">

    <div class="col-md-3">
        <div class="bg-primary p-4">
            <span class="h1">89<span>
                <p class="h5">Produtos Cadastrados</p>
                <a href="/produtos" class="btn btn-light">
                    Ver com olhos
                </a>
        </div>
    </div>

    <div class="col-md-3">
        <div class="bg-success p-4">
            <span class="h1">89<span>
                <p class="h5">Usuários Cadastrados</p>
                <a href="/usuarios" class="btn btn-light">
                    Ver com olhos
                </a>
        </div>
    </div>

    <div class="col-md-3">
        <div class="bg-info p-4">
            <span class="h1">89<span>
                <p class="h5">Categorias</p>
                <a href="/categorias" class="btn btn-light">
                    Ver com olhos
                </a>
        </div>
    </div>

    <div class="col-md-3">
        <div class="bg-warning p-4">
            <span class="h1">89<span>
                <p class="h5">Pedidos Finalizados</p>
                <a href="/pedidos" class="btn btn-light">
                    Ver com olhos
                </a>
        </div>
    </div>

</section>