

<section class="row mt-5">


    <div class="col-md-8 bg-dark text-white card card-body ">
        <h1>Bem vindo...</h1>
        <h2>Sistema de controle de estoque</h2>    

    </div>

    <div class="col-md-4 card card-body" >
        <form method="post" action="">
            <input type="text" placeholder="Login" class="form-control"><br>
            <input type="password" placeholder="Password" class="form-control"><br>
            <button class="btn btn-primary btn-block">Entrar</button>
        </form>
    </div>

</section>