<section class="row mt-5">
  <div class="col-md-8 card bg-dark text-white card-body">
    <h1>Bem vindo...</h1>
    <h3>Sistema de Controle de Estoque</h3>
  </div>

  <div class="col-md-4 card card-body">
    <form action="" method="post">
      <legend></legend>

      <label for="email">Email: </label>
      <input id="email" type="email" class="form-control">

      <label for="password">Senha: </label>
      <input id="password" type="password" class="form-control">

      <button class="mt-3 btn btn-dark btn-block">ENTRAR</button>
    </form>
  </div>
</section>
